### ISSUE TITLE
Issues on non-Volla phone (Poco F3, MIUI 14, A13)

### ISSUE THREAD

**Issue by mazimmer** [HelloVolla/android-launcher-qt#122]
Built from HEAD, v2.1.14 and v2.1.13, installed on A13 (MIUI 14). Gave all permissions available.
Unfortunately:
- no Apps nor Contacts are being found/displayed.
- Websearch can't be initiated (tapping doesn't do anything)
- Translucent setting is ignored; dark/light work

After using it for a bit, it turns into a plain black screen. Then I have to clear all data and give all permissions manually, but also that doesn't fix the last issue consistently.

Anything I can do?

**Comment by wurzer** [comment]
The Volla launcher is developed ans licensed only for Volla OS on Volla Devices. However you can build the Volla launcher yourself for any platform. 

Please make sure, that you have granted all required permissions. The Volla launcher uses a standard Android API. Please note, that the people collection only shows only your contact favorites and the people four have been in contact recently.

Web search should work, because of a quite simple API call. I suggest to have a look at the logs.You are welcome topost the relevant snippet here.

**Comment by mazimmer** [comment]
I have granted all possible permissions.
The log excerpt below seems to have a few errors, do you see any relevant ones?

```
[02-27 11:07:35.912 21933:21933 D/.volla.launcher]
JNI_OnLoad success

[02-27 11:07:36.065 21933:21963 I/Qt JAVA]
Can't find '/data/user/0/com.volla.launcher/qt-reserved-files/lib/libQt5QuickParticles.so'


[02-27 11:07:36.126 2193:7955 D/WindowManager]
Input focus has changed to Window{ed319d9 u0 com.volla.launcher/com.volla.launcher.activity.ReceiveTextActivity} display=0 updateInputWindows = true

[02-27 11:07:36.126 2193:2243 D/WindowManager]
Update InputWindowHandle: ed319d9 com.volla.launcher/com.volla.launcher.activity.ReceiveTextActivity, frame=[0,0,0,0], touchableRegion=SkRegion((0,0,1080,2400)), scaleFactor=1.0, transform=null, windowToken=android.os.BinderProxy@a4c0c20, isClone=false, visibal=true, focusable=true, changed=true

[02-27 11:07:36.130 1377:2888 I/SurfaceFlinger]
setTransactionState focusRequest transactionId:9418863339719 frontWin:ed319d9 com.volla.launcher/com.volla.launcher.activity.ReceiveTextActivity

[02-27 11:07:36.151 21933:21956 D/.volla.launcher]
MiuiProcessManagerServiceStub setSchedFifo

[02-27 11:07:36.160 2193:7955 D/WindowManager]
finishDrawingLocked: mDrawState=COMMIT_DRAW_PENDING Window{ed319d9 u0 com.volla.launcher/com.volla.launcher.activity.ReceiveTextActivity} in Surface(name=com.volla.launcher/com.volla.launcher.activity.ReceiveTextActivity)/@0xc89061a

[02-27 11:07:36.485 21933:21963 D/Volla Launcher]
qml: Springboard | update model for 

[02-27 11:07:36.488 21933:21963 D/Volla Launcher]
Data Path:  "/storage/emulated/0/Documents"

[02-27 11:07:36.504 5729:20096 E/MediaProvider]
Permission to access file: /storage/emulated/0/Documents/.shortcuts.json is denied uid = 10167
java.lang.SecurityException: com.volla.launcher has no access to content://media/external_primary/file/1000004197
	at com.android.providers.media.MediaProvider.enforceCallingPermissionInternal(Unknown Source:328)
	at com.android.providers.media.MediaProvider.enforceCallingPermission(Unknown Source:5)
	at com.android.providers.media.MediaProvider.checkAccess(Unknown Source:15)
	at com.android.providers.media.MediaProvider.checkIfFileOpenIsPermitted(Unknown Source:84)
	at com.android.providers.media.MediaProvider.onFileOpenForFuse(Unknown Source:299)

[02-27 11:07:36.504 21933:21963 D/Volla Launcher]
qml: MainView | Shortcut settings error: Unable to open the file

[02-27 11:07:36.504 21933:21963 D/Volla Launcher]
qml: MainView | Retrieved shortcuts: 

[02-27 11:07:36.521 21933:21963 D/Volla Launcher]
qml: AppGrid | Column completed

[02-27 11:07:36.523 21933:21963 D/Volla Launcher]
qml: Settings | Blurr filter chanded to 30

[02-27 11:07:36.524 21933:21963 W/Volla Launcher]
qrc:/main.qml:839: TypeError: Property 'sync' of object QQmlSettings_QML_13(0x72238cdb80) is not a function

[02-27 11:07:36.535 639:639 E/SELinux]
avc:  denied  { find } for pid=21933 uid=10167 name=vollachildmode scontext=u:r:untrusted_app_29:s0:c167,c256,c512,c768 tcontext=u:object_r:default_android_service:s0 tclass=service_manager permissive=0

[02-27 11:07:36.536 21933:21963 D/Volla Launcher]
qml: Settings | Running changed to true

[02-27 11:07:36.536 21933:21963 D/Volla Launcher]
qml: Settings | Switch off security option labels

[02-27 11:07:36.536 21933:21963 D/Volla Launcher]
qml: Settings | Switch off mode option labels

[02-27 11:07:36.547 21933:21933 D/SurfaceView]
UPDATE Surface(name=SurfaceView[com.volla.launcher/com.volla.launcher.activity.ReceiveTextActivity])/@0x25b2fc6, mIsProjectionMode = false

[02-27 11:07:36.607 21933:21963 D/Volla Launcher]
qml: MainView | Current themes: 1, 1

[02-27 11:07:36.610 21933:21963 W/Volla Launcher]
qrc:/main.qml:1000: TypeError: Property 'sync' of object QQmlSettings_QML_13(0x72238cdb80) is not a function

[02-27 11:07:36.624 21933:21963 D/Volla Launcher]
qml: AppGrid | Pinned shortcuts received: 0

[02-27 11:07:36.624 21933:21933 D/WallpaperManagerImpl]
notifyWallpaperChanged, which = 2 userId = 0 callingPackage = com.volla.launcher

[02-27 11:07:36.624 21933:21963 D/Volla Launcher]
qml: Settings | Security state: false, Not installed
```

**Comment by wurzer** [comment]
Die Exception wird ausgegeben, weil der Launcher keine Berechtigung hat, auf den Dokumenten-Ordner zuzugreifen. Das ist aber nur relevant für die Speicherung von Notizen und Einstellungen für News-Feeds und Kurzbefehlen. 

Sie können dafür den Ablageort in fileio.cpp oder die Aufrufe für das speichern und abfragen von Dateien im QML quellcode in savePrivate und readPrivate ändern. 

Bezäglich des URL und Kontakte Aufrufs muss es aber noch weiteren Log geben.
